name: Build and publish
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install mkdocs dependencies
        run: pip install mkdocs mkdocs-material

      - name: Build mkdocs documentation
        run: mkdocs build

      - name: Publish to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy -d site -p
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
